sudo: required
dist: trusty

# install the pre-release chef-dk.  Use chef-stable-precise to install the stable release
addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=default-centos-6
  - INSTANCE=default-centos-7
  - INSTANCE=default-debian-7
  - INSTANCE=default-debian-8
  - INSTANCE=default-fedora-latest
  - INSTANCE=default-opensuse-421
  - INSTANCE=default-ubuntu-1204
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1604
  - INSTANCE=source-centos-6
  - INSTANCE=source-centos-7
  - INSTANCE=source-debian-7
  - INSTANCE=source-debian-8
  - INSTANCE=source-fedora-latest
  - INSTANCE=source-opensuse-132
  - INSTANCE=source-opensuse-421
  - INSTANCE=source-ubuntu-1204
  - INSTANCE=source-ubuntu-1404
  - INSTANCE=source-ubuntu-1604
  - INSTANCE=modules-centos-6
  - INSTANCE=modules-centos-7
  - INSTANCE=modules-debian-7
  - INSTANCE=modules-debian-8
  - INSTANCE=modules-fedora-latest
  - INSTANCE=modules-opensuse-132
  - INSTANCE=modules-opensuse-421
  - INSTANCE=modules-ubuntu-1204
  - INSTANCE=modules-ubuntu-1404
  - INSTANCE=modules-ubuntu-1604
  - INSTANCE=upstream-repo-centos-6
  - INSTANCE=upstream-repo-centos-7
  - INSTANCE=upstream-repo-debian-7
  - INSTANCE=upstream-repo-debian-8
  - INSTANCE=upstream-repo-opensuse-132
  - INSTANCE=upstream-repo-opensuse-421
  - INSTANCE=upstream-repo-ubuntu-1204
  - INSTANCE=upstream-repo-ubuntu-1404
  - INSTANCE=upstream-repo-ubuntu-1604

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"

script: KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

matrix:
  include:
    - before_script:
      - eval "$(/opt/chefdk/bin/chef shell-init bash)"
      - /opt/chefdk/embedded/bin/chef --version
      - /opt/chefdk/embedded/bin/cookstyle --version
      - /opt/chefdk/embedded/bin/foodcritic --version
    - script:
      - /opt/chefdk/bin/chef exec rake
      env: UNIT_AND_LINT=1
