---
lint_and_unit: &lint_and_unit
  - delivery
  - danger
  - lint-yaml
  - lint-markdown

version: 2.1

orbs:
  kitchen: sous-chefs/kitchen@2.0.2

workflows:
  kitchen:
    jobs:
      # Lint and Unit Test
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/delivery:
          name: delivery

      # distro
      - kitchen/dokken-single:
          name: distro-amazonlinux-2
          suite: distro-amazonlinux-2
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: distro-debian-8
          suite: distro-debian-8
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: distro-debian-9
          suite: distro-debian-9
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: distro-ubuntu-1604
          suite: distro-ubuntu-1604
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: distro-ubuntu-1804
          suite: distro-ubuntu-1804
          requires:
            *lint_and_unit

      # repo
      - kitchen/dokken-single:
          name: repo-amazonlinux-2
          suite: repo-amazonlinux-2
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: repo-centos-7
          suite: repo-centos-7
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: repo-debian-8
          suite: repo-debian-8
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: repo-debian-9
          suite: repo-debian-9
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: repo-ubuntu-1604
          suite: repo-ubuntu-1604
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: repo-ubuntu-1804
          suite: repo-ubuntu-1804
          requires:
            *lint_and_unit

      # epel
      - kitchen/dokken-single:
          name: epel-amazonlinux-2
          suite: epel-amazonlinux-2
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: epel-centos-7
          suite: epel-centos-7
          requires:
            *lint_and_unit

      # passenger
      - kitchen/dokken-single:
          name: passenger-debian-8
          suite: passenger-debian-8
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: passenger-debian-9
          suite: passenger-debian-9
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: passenger-ubuntu-1604
          suite: passenger-ubuntu-1604
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: passenger-ubuntu-1804
          suite: passenger-ubuntu-1804
          requires:
            *lint_and_unit
